CREATE TABLE user_read_feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    feed_id INTEGER NOT NULL,
    read_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_user_read_feeds_user_feed UNIQUE (user_id, feed_id),
    CONSTRAINT fk_user_read_feeds_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_read_feeds_feed
        FOREIGN KEY (feed_id) REFERENCES feeds (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_read_feeds_user_read
    ON user_read_feeds (user_id, read_at DESC, id ASC);

CREATE INDEX idx_user_read_feeds_feed
    ON user_read_feeds (feed_id);
