CREATE TABLE user_read_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    read_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_user_read_history_user_article UNIQUE (user_id, article_id),
    CONSTRAINT fk_user_read_history_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_read_history_article
        FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_read_history_user_read
    ON user_read_history (user_id, read_at DESC, id ASC);

CREATE INDEX idx_user_read_history_article
    ON user_read_history (article_id);
