CREATE TABLE user_collection_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_collection_folders_uid UNIQUE (uid),
    CONSTRAINT uq_collection_folders_user_name UNIQUE (user_id, name),
    CONSTRAINT uq_collection_folders_user_id UNIQUE (user_id, id),
    CONSTRAINT ck_collection_folders_name CHECK (name = btrim(name) AND char_length(name) > 0),
    CONSTRAINT fk_collection_folders_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    folder_id BIGINT,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_collections_user_article UNIQUE (user_id, article_id),
    CONSTRAINT fk_user_collections_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_collections_article
        FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_collections_folder
        FOREIGN KEY (user_id, folder_id) REFERENCES user_collection_folders (user_id, id)
);

CREATE INDEX idx_collection_folders_user_created
    ON user_collection_folders (user_id, created_at DESC, id ASC);

CREATE INDEX idx_user_collections_user_collected
    ON user_collections (user_id, collected_at DESC, id ASC);

CREATE INDEX idx_user_collections_user_folder_collected
    ON user_collections (user_id, folder_id, collected_at DESC, id ASC);

CREATE INDEX idx_user_collections_article ON user_collections (article_id);

CREATE TABLE user_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    liked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_likes_user_article UNIQUE (user_id, article_id),
    CONSTRAINT fk_user_likes_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_likes_article
        FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_likes_user_liked ON user_likes (user_id, liked_at DESC, id ASC);

CREATE INDEX idx_user_likes_article ON user_likes (article_id);
